prefix def: <http://purl.obolibrary.org/obo/IAO_0000115>
prefix owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (STRAFTER(STR(?term), "http://purl.obolibrary.org/obo/") as ?IRI) ?value ?def
WHERE {
  ?term a owl:AnnotationProperty .
  ?term rdfs:label ?value .
  OPTIONAL { ?term def: ?def }  .
  FILTER contains(STR(?term), "OpenLHS-Core_")
  }
  ORDER BY ?IRI